use_frameworks!

target 'DTPhotoViewerController_Example' do
  pod 'DTPhotoViewerController', :path => '../'
end

target 'DTPhotoViewerController_Tests' do
  pod 'DTPhotoViewerController', :path => '../'
end


